-- Inserindo Equipes de Teste
INSERT INTO T_EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE) VALUES ('Equipe Alfa', 'Roçada Mecanizada');
INSERT INTO T_EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE) VALUES ('Equipe Beta', 'Pulverização');

-- Inserindo Trechos de Teste
INSERT INTO T_TRECHO_RODOVIA (QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO, TIPO_CLIMA, ID_EQUIPE)
VALUES (0.0, 10.0, 12.0, 'Seco', 1);

INSERT INTO T_TRECHO_RODOVIA (QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO, TIPO_CLIMA, ID_EQUIPE)
VALUES (10.0, 20.0, 25.0, 'Úmido', 2);

INSERT INTO T_TRECHO_RODOVIA (QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO, TIPO_CLIMA, ID_EQUIPE)
VALUES (20.0, 30.0, 5.0, 'Seco', 1);

-- Inserindo Intervenções de Teste (Registros de serviços executados)
INSERT INTO T_INTERVENCAO_OPERACIONAL (TIPO_INTERVENCAO, DATA_INTERVENCAO, ID_TRECHO)
VALUES ('RocadaMecanizada', SYSDATE, 2);

INSERT INTO T_INTERVENCAO_OPERACIONAL (TIPO_INTERVENCAO, DATA_INTERVENCAO, ID_TRECHO)
VALUES ('Pulverizacao', SYSDATE, 1);

-- Confirma a gravação dos dados no Oracle
COMMIT;