-- Limpeza prévia de tabelas anteriores (se existirem)
DROP TABLE T_RELATORIO_PRIORIDADE CASCADE CONSTRAINTS;
DROP TABLE T_INTERVENCAO_OPERACIONAL CASCADE CONSTRAINTS;
DROP TABLE T_TRECHO_RODOVIA CASCADE CONSTRAINTS;
DROP TABLE T_EQUIPE_MANUTENCAO CASCADE CONSTRAINTS;

-- Tabela correspondente à classe EquipeManutencao
CREATE TABLE T_EQUIPE_MANUTENCAO (
                                     ID_EQUIPE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     NOME VARCHAR2(100) NOT NULL,
                                     ESPECIALIDADE VARCHAR2(100) NOT NULL
);

-- Tabela correspondente à classe TrechoRodovia
CREATE TABLE T_TRECHO_RODOVIA (
                                  ID_TRECHO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  QUILOMETRO_INICIAL NUMBER(8,2) NOT NULL,
                                  QUILOMETRO_FINAL NUMBER(8,2) NOT NULL,
                                  NIVEL_VEGETACAO NUMBER(8,2) NOT NULL,
                                  TIPO_CLIMA VARCHAR2(50) NOT NULL,
                                  ID_EQUIPE NUMBER,
                                  CONSTRAINT FK_TRECHO_EQUIPE FOREIGN KEY (ID_EQUIPE)
                                      REFERENCES T_EQUIPE_MANUTENCAO(ID_EQUIPE) ON DELETE SET NULL
);

-- Tabela correspondente à hierarquia IntervencaoOperacional
CREATE TABLE T_INTERVENCAO_OPERACIONAL (
                                           ID_INTERVENCAO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           TIPO_INTERVENCAO VARCHAR2(100) NOT NULL,
                                           DATA_INTERVENCAO DATE DEFAULT SYSDATE NOT NULL,
                                           ID_TRECHO NUMBER NOT NULL,
                                           CONSTRAINT FK_INTERVENCAO_TRECHO FOREIGN KEY (ID_TRECHO)
                                               REFERENCES T_TRECHO_RODOVIA(ID_TRECHO) ON DELETE CASCADE
);

-- Tabela para persistência do histórico do GeradorRelatorio
CREATE TABLE T_RELATORIO_PRIORIDADE (
                                        ID_RELATORIO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        QT_URGENTE NUMBER NOT NULL,
                                        QT_CRITICO NUMBER NOT NULL,
                                        QT_ATENCAO NUMBER NOT NULL,
                                        QT_NORMAL NUMBER NOT NULL,
                                        RESUMO VARCHAR2(1000) NOT NULL,
                                        DATA_GERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);